import '@testing-library/jest-dom/vitest'
import { cleanup } from '@testing-library/react'
import { afterEach, vi } from 'vitest'

// Mock pdfjs-dist (not available in jsdom test environment)
vi.mock('pdfjs-dist', () => ({
  GlobalWorkerOptions: { workerSrc: '' },
  getDocument: vi.fn(() => ({
    promise: Promise.resolve({
      getPage: vi.fn(() => Promise.resolve({
        getViewport: vi.fn(() => ({ width: 100, height: 100 })),
        render: vi.fn(() => ({ promise: Promise.resolve() })),
      })),
      destroy: vi.fn(),
    }),
  })),
}))

// Cleanup DOM after each test
afterEach(() => {
  cleanup()
})

// Polyfill scrollIntoView for jsdom (not supported natively)
Element.prototype.scrollIntoView = vi.fn()

// Mock window.kanbai global API (Electron preload bridge)
// Use Object.defineProperty to add to the existing jsdom window without replacing it
const mockMirehub = {
  settings: {
    get: vi.fn().mockResolvedValue({
      theme: 'dark',
      locale: 'fr',
      defaultShell: '/bin/zsh',
      fontSize: 13,
      fontFamily: 'Menlo',
      scrollbackLines: 5000,
      claudeDetectionColor: '#7c3aed',
      autoClauderEnabled: false,
      notificationSound: true,
      notificationBadge: true,
      checkUpdatesOnLaunch: true,
      autoCloseCompletedTerminals: false,
      autoCloseCtoTerminals: true,
      autoApprove: true,
      tutorialCompleted: false,
      tutorialSeenSections: [],
    }),
    set: vi.fn().mockResolvedValue(undefined),
  },
  fs: {
    readDir: vi.fn().mockResolvedValue([]),
    readFile: vi.fn().mockResolvedValue({ content: null, error: null }),
    readBase64: vi.fn().mockResolvedValue({ data: null, error: null }),
    writeFile: vi.fn().mockResolvedValue({ success: true, error: null }),
    rename: vi.fn().mockResolvedValue(undefined),
    exists: vi.fn().mockResolvedValue(false),
    copy: vi.fn().mockResolvedValue(undefined),
    delete: vi.fn().mockResolvedValue(undefined),
    mkdir: vi.fn().mockResolvedValue(undefined),
    openInFinder: vi.fn().mockResolvedValue(undefined),
    search: vi.fn().mockResolvedValue([]),
  },
  kanban: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    watch: vi.fn(),
    unwatch: vi.fn(),
    onFileChanged: vi.fn().mockReturnValue(() => {}),
    writePrompt: vi.fn(),
    listPromptTemplates: vi.fn().mockResolvedValue([]),
    attachFiles: vi.fn(),
    attachFromClipboard: vi.fn(),
    removeAttachment: vi.fn(),
    listAttachments: vi.fn().mockResolvedValue([]),
    selectFiles: vi.fn().mockResolvedValue([]),
    attachFile: vi.fn().mockResolvedValue(undefined),
    watchRemove: vi.fn(),
    watchAdd: vi.fn(),
    getConfig: vi.fn().mockResolvedValue({}),
    setConfig: vi.fn().mockResolvedValue(undefined),
    getDefaultConfig: vi.fn().mockResolvedValue({}),
    setDefaultConfig: vi.fn().mockResolvedValue(undefined),
    prequalify: vi.fn().mockResolvedValue(null),
    linkConversation: vi.fn().mockResolvedValue(null),
    getWorkingTicket: vi.fn().mockResolvedValue(null),
    getWorkingTickets: vi.fn().mockResolvedValue([]),
    evaluateTemplateConditions: vi.fn().mockResolvedValue([]),
    executeTemplateAction: vi.fn().mockResolvedValue({ success: true }),
    onTaskProgress: vi.fn().mockReturnValue(() => {}),
  },
  gitConfig: {
    get: vi.fn().mockResolvedValue({ userName: '', userEmail: '', isCustom: false }),
    set: vi.fn().mockResolvedValue(undefined),
    delete: vi.fn().mockResolvedValue(undefined),
  },
  ssh: {
    listKeys: vi.fn().mockResolvedValue({ success: true, keys: [] }),
    generateKey: vi.fn(),
    importKey: vi.fn(),
    deleteKey: vi.fn(),
    selectKeyFile: vi.fn(),
    readPublicKey: vi.fn(),
    openDirectory: vi.fn(),
  },
  namespace: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    ensureDefault: vi.fn().mockResolvedValue(undefined),
  },
  app: {
    version: vi.fn().mockResolvedValue({ version: '0.1.0', name: 'Mirehub' }),
    checkForUpdate: vi.fn(),
  },
  workspace: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    permanentDelete: vi.fn().mockResolvedValue(undefined),
    checkDeleted: vi.fn().mockResolvedValue(null),
    restore: vi.fn().mockResolvedValue(null),
    export: vi.fn().mockResolvedValue({ success: true }),
    import: vi.fn().mockResolvedValue({ success: true }),
  },
  project: {
    list: vi.fn().mockResolvedValue([]),
    selectDir: vi.fn(),
    add: vi.fn(),
    remove: vi.fn(),
    scanClaude: vi.fn(),
    scanInfo: vi.fn().mockResolvedValue({ name: '', type: '' }),
    checkClaude: vi.fn().mockResolvedValue({ configured: false }),
    deployClaude: vi.fn().mockResolvedValue({ success: true }),
    checkPackages: vi.fn().mockResolvedValue({ packages: [] }),
    updatePackage: vi.fn().mockResolvedValue({ success: true }),
    writeClaudeSettings: vi.fn().mockResolvedValue({ success: true }),
    writeClaudeMd: vi.fn().mockResolvedValue({ success: true }),
    readClaudeLocalSettings: vi.fn().mockResolvedValue(null),
    writeClaudeLocalSettings: vi.fn().mockResolvedValue({ success: true }),
    readUserClaudeSettings: vi.fn().mockResolvedValue(null),
    writeUserClaudeSettings: vi.fn().mockResolvedValue({ success: true }),
    scanTodos: vi.fn().mockResolvedValue([]),
    loadIgnoredTodos: vi.fn().mockResolvedValue([]),
    saveIgnoredTodos: vi.fn().mockResolvedValue({ success: true }),
    stats: vi.fn().mockResolvedValue({}),
    getNotes: vi.fn().mockResolvedValue(''),
    saveNotes: vi.fn().mockResolvedValue({ success: true }),
  },
  workspaceEnv: {
    setup: vi.fn(),
    getPath: vi.fn(),
    delete: vi.fn(),
  },
  prompts: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  shell: {
    openExternal: vi.fn().mockResolvedValue({ success: true }),
  },
  packages: {
    detect: vi.fn().mockResolvedValue([]),
    list: vi.fn().mockResolvedValue({ packages: [] }),
    update: vi.fn().mockResolvedValue({ success: true }),
    search: vi.fn().mockResolvedValue({ results: [] }),
    nlAsk: vi.fn().mockResolvedValue({ answer: '' }),
    nlCancel: vi.fn().mockResolvedValue(undefined),
  },
  analysis: {
    detectTools: vi.fn().mockResolvedValue([]),
    run: vi.fn().mockResolvedValue({}),
    cancel: vi.fn().mockResolvedValue({ success: true }),
    loadReports: vi.fn().mockResolvedValue([]),
    deleteReport: vi.fn().mockResolvedValue({ success: true }),
    createTickets: vi.fn().mockResolvedValue({ success: true, ticketCount: 0 }),
    onProgress: vi.fn().mockReturnValue(() => {}),
    installTool: vi.fn().mockResolvedValue({ success: true, installed: true }),
    onInstallProgress: vi.fn().mockReturnValue(() => {}),
  },
  healthcheck: {
    load: vi.fn().mockResolvedValue({ checks: [], history: [] }),
    save: vi.fn().mockResolvedValue({ success: true }),
    execute: vi.fn().mockResolvedValue({}),
    startScheduler: vi.fn().mockResolvedValue({ success: true }),
    stopScheduler: vi.fn().mockResolvedValue({ success: true }),
    updateInterval: vi.fn().mockResolvedValue({ success: true }),
    getStatuses: vi.fn().mockResolvedValue([]),
    export: vi.fn().mockResolvedValue({ success: true }),
    import: vi.fn().mockResolvedValue({ success: true }),
    clearHistory: vi.fn().mockResolvedValue({ success: true }),
    onStatusUpdate: vi.fn().mockReturnValue(() => {}),
  },
  database: {
    connect: vi.fn().mockResolvedValue(undefined),
    disconnect: vi.fn().mockResolvedValue(undefined),
    testConnection: vi.fn().mockResolvedValue({ success: true }),
    listDatabases: vi.fn().mockResolvedValue([]),
    listSchemas: vi.fn().mockResolvedValue([]),
    listTables: vi.fn().mockResolvedValue([]),
    tableInfo: vi.fn().mockResolvedValue({}),
    executeQuery: vi.fn().mockResolvedValue({ columns: [], rows: [], rowCount: 0, executionTime: 0 }),
    cancelQuery: vi.fn().mockResolvedValue(undefined),
    load: vi.fn().mockResolvedValue({ connections: [], queries: [] }),
    save: vi.fn().mockResolvedValue({ success: true }),
    export: vi.fn().mockResolvedValue({ success: true }),
    import: vi.fn().mockResolvedValue({ success: true }),
    backup: vi.fn().mockResolvedValue({ success: true }),
    onBackupLog: vi.fn().mockReturnValue(() => {}),
    backupList: vi.fn().mockResolvedValue({ success: true, entries: [] }),
    backupDelete: vi.fn().mockResolvedValue({ success: true }),
    restore: vi.fn().mockResolvedValue({ success: true }),
    transfer: vi.fn().mockResolvedValue({ success: true, errors: [] }),
    nlQuery: vi.fn().mockResolvedValue({}),
    nlGenerateSql: vi.fn().mockResolvedValue({}),
    nlInterpret: vi.fn().mockResolvedValue({}),
    nlCancel: vi.fn().mockResolvedValue({ success: true }),
    getSchemaContext: vi.fn().mockResolvedValue(''),
  },
  terminal: {
    create: vi.fn().mockResolvedValue({ id: 'mock-session-id', pid: 12345 }),
    write: vi.fn(),
    resize: vi.fn(),
    close: vi.fn().mockResolvedValue(undefined),
    onData: vi.fn().mockReturnValue(() => {}),
    onClose: vi.fn().mockReturnValue(() => {}),
  },
  claude: {
    start: vi.fn(),
    stop: vi.fn(),
    status: vi.fn().mockResolvedValue([]),
    onSessionEnd: vi.fn().mockReturnValue(() => {}),
    onActivity: vi.fn().mockReturnValue(() => {}),
    installHooks: vi.fn().mockResolvedValue({ success: true }),
    checkHooks: vi.fn().mockResolvedValue({ installed: false }),
  },
  git: {
    status: vi.fn().mockResolvedValue({ files: [], branch: 'main', ahead: 0, behind: 0 }),
    log: vi.fn().mockResolvedValue([]),
    branches: vi.fn().mockResolvedValue([]),
    diff: vi.fn().mockResolvedValue(''),
    commit: vi.fn().mockResolvedValue(undefined),
    push: vi.fn().mockResolvedValue(undefined),
    pull: vi.fn().mockResolvedValue(undefined),
    checkout: vi.fn().mockResolvedValue(undefined),
    stage: vi.fn().mockResolvedValue(undefined),
    unstage: vi.fn().mockResolvedValue(undefined),
    discard: vi.fn().mockResolvedValue(undefined),
    stash: vi.fn().mockResolvedValue(undefined),
    stashPop: vi.fn().mockResolvedValue(undefined),
    createBranch: vi.fn().mockResolvedValue(undefined),
    deleteBranch: vi.fn().mockResolvedValue(undefined),
    merge: vi.fn().mockResolvedValue(undefined),
    fetch: vi.fn().mockResolvedValue(undefined),
    init: vi.fn().mockResolvedValue(undefined),
  },
  mcp: {
    getHelp: vi.fn().mockResolvedValue({}),
    workspaceRead: vi.fn().mockResolvedValue({ mcpServers: {} }),
    workspaceWrite: vi.fn().mockResolvedValue({ success: true }),
  },
  updates: {
    check: vi.fn().mockResolvedValue(undefined),
    install: vi.fn().mockResolvedValue({ success: true }),
    uninstall: vi.fn().mockResolvedValue({ success: true }),
    onStatus: vi.fn().mockReturnValue(() => {}),
  },
  appUpdate: {
    check: vi.fn().mockResolvedValue({ success: true }),
    download: vi.fn().mockResolvedValue({ success: true }),
    install: vi.fn().mockResolvedValue(undefined),
    onStatus: vi.fn().mockReturnValue(() => {}),
  },
  devops: {
    load: vi.fn().mockResolvedValue({ connections: [], pipelines: [] }),
    save: vi.fn().mockResolvedValue({ success: true }),
    testConnection: vi.fn().mockResolvedValue({ success: true }),
    listPipelines: vi.fn().mockResolvedValue({ success: true, pipelines: [] }),
    getPipelineRuns: vi.fn().mockResolvedValue({ success: true, runs: [] }),
    runPipeline: vi.fn().mockResolvedValue({ success: true }),
    getBuildTimeline: vi.fn().mockResolvedValue({ success: true, stages: [] }),
    getApprovals: vi.fn().mockResolvedValue({ success: true, approvals: [] }),
    approve: vi.fn().mockResolvedValue({ success: true }),
    getBuildLog: vi.fn().mockResolvedValue({ success: true, content: '' }),
  },
  notify: vi.fn(),
  onMenuAction: vi.fn().mockReturnValue(() => {}),
  clipboard: {
    writeText: vi.fn(),
    readText: vi.fn().mockReturnValue(''),
  },
  notes: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
  session: {
    save: vi.fn().mockResolvedValue(undefined),
    load: vi.fn().mockResolvedValue(null),
    clear: vi.fn().mockResolvedValue(undefined),
  },
  aiProvider: {
    set: vi.fn().mockResolvedValue(undefined),
    checkInstalled: vi.fn().mockResolvedValue({}),
    checkMultiAgent: vi.fn().mockResolvedValue({ enabled: false }),
  },
  claudeMemory: {
    readAuto: vi.fn().mockResolvedValue({ content: '', topicFiles: [] }),
    toggleAuto: vi.fn().mockResolvedValue({ success: true }),
    listRules: vi.fn().mockResolvedValue({ rules: [], directories: [] }),
    readRule: vi.fn().mockResolvedValue(null),
    writeRule: vi.fn().mockResolvedValue({ success: true }),
    deleteRule: vi.fn().mockResolvedValue({ success: true }),
  },
  claudeDefaults: {
    profiles: vi.fn().mockResolvedValue([]),
    skills: vi.fn().mockResolvedValue([]),
    deployProfile: vi.fn().mockResolvedValue({ success: true }),
    deploySkill: vi.fn().mockResolvedValue({ success: true }),
    checkDeployed: vi.fn().mockResolvedValue({ deployedProfiles: [], deployedSkills: [] }),
  },
  skillsStore: {
    fetch: vi.fn().mockResolvedValue({ repos: [], skills: [] }),
    install: vi.fn().mockResolvedValue({ success: true }),
  },
  api: {
    execute: vi.fn().mockResolvedValue({ response: {}, testResults: [] }),
    load: vi.fn().mockResolvedValue({ collections: [], variables: {} }),
    save: vi.fn().mockResolvedValue({ success: true }),
    export: vi.fn().mockResolvedValue({ success: true }),
    import: vi.fn().mockResolvedValue({ success: true, data: null }),
  },
}

// Add mirehub to the jsdom window without replacing the whole window object
Object.defineProperty(window, 'kanbai', {
  value: mockMirehub,
  writable: true,
  configurable: true,
})
